version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    command: ["redis-server", "--requirepass", "redis"]
    volumes:
      - redis_data:/data

volumes:
  redis_data:
    driver: local
