version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_container
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=redis
    command: ["redis-server", "--requirepass", "redis"]
    volumes:
      - redis_data:/data

  minio:
    image: minio/minio
    container_name: minio_container
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio124
    command: server /export --console-address ":9001"
    volumes:
      - /mnt/hdd/minio/data:/export
      - /mnt/hdd/minio/config:/root/.minio

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    volumes:
      - mongo_data:/data/db

volumes:
  redis_data:
    driver: local
  mongo_data:
    driver: local
